version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ubuntu/todolist
hooks:
    BeforeInstall:
        - location: scripts/beforeInstall.sh
    ApplicationStart:
        - location: scripts/appStart.sh
