version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ubuntu/todolist
hooks:
    BeforeInstall:
        - location: /home/ubuntu/scripts/beforeInstall.sh
    AfterInstall:
        - location: /home/ubuntu/scripts/afterInstall.sh
